server:
    error:
        include-message: always
    port: 7070
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: 1234
        url: jdbc:postgresql://localhost:5432/restaurant
        username: postgres
    jpa:
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
        show-sql: true
    jwt:
        secret_key: java8IsTheBestGroup
